#include "GPIO_cfg.h"

const GPIO_ConfigType PortsConfig [PINS_NUM] =
{
	{GPIO_DEN, GPIO_PIN_HIGH, GPIO_PIN_OUTPUT, GPIO_PULL_DOWN, GPIO_4mA, GPIO_PORT_C, GPIO_PIN_4},
	{GPIO_DEN, GPIO_PIN_HIGH, GPIO_PIN_OUTPUT, GPIO_PULL_DOWN, GPIO_8mA, GPIO_PORT_C, GPIO_PIN_5},
	{GPIO_DEN, GPIO_PIN_HIGH, GPIO_PIN_OUTPUT, GPIO_PULL_DOWN, GPIO_8mA, GPIO_PORT_C, GPIO_PIN_6}
};
