#include "GPIO_Lcfg.h"

const GPIO_ConfigType PortsConfig [PINS_NUM] =
{
	{GPIO_DEN, GPIO_PIN_HIGH, GPIO_PIN_OUTPUT, GPIO_PULL_DOWN, GPIO_2mA, GPIO_PORT_F, GPIO_PIN_0},
	{GPIO_DEN, GPIO_PIN_HIGH, GPIO_PIN_OUTPUT, GPIO_PULL_DOWN, GPIO_4mA, GPIO_PORT_F, GPIO_PIN_1},
	{GPIO_DEN, GPIO_PIN_HIGH, GPIO_PIN_OUTPUT, GPIO_PULL_DOWN, GPIO_8mA, GPIO_PORT_F, GPIO_PIN_2}
};
