#include "IntCtrl_Config.h"

const ST_IntCtrl_ConfigType_t IntCtrlConfigPtr[INTS_NUM] =
{
	{ INTCTRL_PORTF_INT_NUM, 3, USE_0_GROUPS_8_SUBGROUPS, INTCTRL_EDGE_TRIGGERED, INTCTRL_RISING, GPIO_PORT_F, GPIO_PIN_0},
	{ INTCTRL_PORTF_INT_NUM, 3, USE_0_GROUPS_8_SUBGROUPS, INTCTRL_EDGE_TRIGGERED, INTCTRL_RISING, GPIO_PORT_F, GPIO_PIN_4}
};