#include "BIT_MATH.h"
#include "GPIO.h"
#include "GPIO_cfg.h"
#include "GPT.h"
#include "GPT_cfg.h"

void TEST_GPIO();
void TEST_Timer();

int main()
{
	//TEST_GPIO();
	TEST_Timer();

	
}

void TEST_GPIO()
{
	SET_BIT(RCGCGPIO, GPIO_PORT_F);
	SET_BIT(GPIODIR(GPIO_PORT_F), GPIO_PIN_1);
	SET_BIT(GPIODEN(GPIO_PORT_F), GPIO_PIN_1);
	while(1)
	{
		GPIODATA(GPIO_PORT_F, GPIO_PIN_1) ^= (1<<GPIO_PIN_1);
		int i=0;
		for(i=0; i<100; i++);
		//CLR_BIT(GPIODATA(GPIO_PORT_F, GPIO_PIN_1), GPIO_PIN_1);
		//for(i=0; i<100; i++);
	}
}

void TEST_Timer()
{
	SET_BIT(RCGCGPIO, GPIO_PORT_F);
	SET_BIT(GPIODIR(GPIO_PORT_F), GPIO_PIN_1);
	SET_BIT(GPIODEN(GPIO_PORT_F), GPIO_PIN_1);
	
	//Timer Initialization
	SET_BIT(RCGCTIMER, TIMER_0_BIT);
	
	CLR_BIT(GPTMCTL(0), TAEN);
	GPTMCFG(TIMER_0_BIT) = GPT_NORMAL_16_VALUE;
	GPTMTAMR(TIMER_0_BIT) = PERIODIC_VALUE;
	GPTMTAPR(TIMER_0_BIT) = 250-1;
	GPTMTAILR(TIMER_0_BIT) = 64000-1;
	SET_BIT(GPTMICR(TIMER_0_BIT), TATOCINT);
	SET_BIT(GPTMIMR(TIMER_0_BIT) ,TATOIM);
	
	SET_BIT(GPTMCTL(0), TAEN);
	
	while(1)
	{
		if(GPTMMIS(0) & (1<<TATOMIS))
		{
			GPIODATA(GPIO_PORT_F, GPIO_PIN_1) ^= (1<<GPIO_PIN_1);
			SET_BIT(GPTMICR(0), TATOCINT);
		}
	}
}