#include "BIT_MATH.h"
#include "GPIO.h"
#include "GPIO_cfg.h"
#include "GPT.h"
#include "GPT_cfg.h"

void TEST_GPIO();
void TEST_Timer();

int main()
{
	//TEST_GPIO();
	TEST_Timer();

	
}

void TEST_GPIO()
{
	SET_BIT(RCGCGPIO, GPIO_PORT_F);
	SET_BIT(GPIODIR(GPIO_PORT_F), GPIO_PIN_1);
	SET_BIT(GPIODEN(GPIO_PORT_F), GPIO_PIN_1);
	while(1)
	{
		TOGGLE_BIT(GPIODATA(GPIO_PORT_F, GPIO_PIN_1), GPIO_PIN_1);
		int i=0;
		for(i=0; i<100; i++);
	}
}

//Timers work up to channel 3; channels 4 and 5 don't blink the LED!!
//1 second delay test
void TEST_Timer()
{
	SET_BIT(RCGCGPIO, GPIO_PORT_F);
	SET_BIT(GPIODIR(GPIO_PORT_F), GPIO_PIN_1);
	SET_BIT(GPIODEN(GPIO_PORT_F), GPIO_PIN_1);
	
	//Timer Initialization
	SET_BIT(RCGCTIMER, TIMER_CHANNEL_3);
	
	CLR_BIT(GPTMCTL(TIMER_CHANNEL_3), TAEN);
	
	GPTMCFG(TIMER_CHANNEL_3) = GPT_NORMAL_16_VALUE;
	GPTMTAMR(TIMER_CHANNEL_3) = PERIODIC_VALUE;
	GPTMTAPR(TIMER_CHANNEL_3) = 250-1;
	GPTMTAILR(TIMER_CHANNEL_3) = 64000-1;
	SET_BIT(GPTMICR(TIMER_CHANNEL_3), TATOCINT);
	SET_BIT(GPTMIMR(TIMER_CHANNEL_3) ,TATOIM);
	
	SET_BIT(GPTMCTL(TIMER_CHANNEL_3), TAEN);
	
	while(1)
	{
		if(GPTMMIS(TIMER_CHANNEL_3) & (1<<TATOMIS))
		{
			TOGGLE_BIT(GPIODATA(GPIO_PORT_F, GPIO_PIN_1), GPIO_PIN_1);
			SET_BIT(GPTMICR(TIMER_CHANNEL_3), TATOCINT);
		}
	}
}